#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  Executable: ${{github.event.repository.name}}.exe # *

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release] #[Release, Debug]
        Settings:
#        - {
#            Name: "Win32",
#            Platform: "Win32",
#            Architecture: "x86",
#            Triplet: "x86-windows"
#          }
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64",
            Triplet: "x64-windows"
          }
          
    steps:

    - name: Clone repo and submodules
      run: >
        git
        clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git
        "${{github.workspace}}"
        --branch ${{env.Branch}}
        --recurse-submodules
        --depth 1

    - name: Cache vcpkg
      uses: actions/cache@v5
      id: cache_vcpkg
      with:
        path: C:/vcpkg/installed
        key: vcpkg-${{hashFiles('**/CMakeLists.txt')}}

    - name: vcpkg
      if: steps.cache_vcpkg.outputs.cache-hit != 'true'
      run: |
        vcpkg install OpenCV onnxruntime tiff --triplet ${{matrix.Settings.Triplet}}

    - name: List files
      run: ls "C:\vcpkg" -R

#        C:\vcpkg\vcpkg install OpenCV --triplet ${{matrix.Settings.Triplet}}
#        git clone https://github.com/microsoft/vcpkg.git --depth 1
#        ./vcpkg/bootstrap-vcpkg.bat
